version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - export NORMAL_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///' | sed 's/pr\///')
      - pip install -qq -U pip wheel
      - pip install -r requirements-dev.txt
      - pip install junit2html
      - mkdir /tmp/artifacts
      - pytest --junit-xml=junit.xml --cov-branch --cov-report=xml --cov=juicebox_cli -vvv
      - junit2html junit.xml || true
      - mv junit.xml.html coverage.xml /tmp/artifacts/
  build:
    commands:
      - cd docs
      - make html
      - |
        if [ "$NORMAL_BRANCH" = "master" ]; then
            aws s3 sync build/html s3://internal.juiceboxdata.com/projects/juicebox-cli --acl bucket-owner-full-control --delete;
            aws s3 sync build/html s3://docs.juiceboxdata.com/projects/juicebox-cli --acl bucket-owner-full-control --delete; fi;
        fi
artifacts:
  files:
    - /tmp/artifacts/*