[pytest]
filterwarnings =
    ignore:.*utcfromtimestamp.*:DeprecationWarning


[tox]
envlist = py{38,39,310,311,312}

[testenv]
python = python3

deps = -r{toxinidir}/requirements-dev.txt
commands =
    check-manifest --ignore tox.ini,tests*,Makefile,circle.yml,pytest.ini,\
      requirements-dev.txt,requirements.txt,docs*,installer*
    python setup.py check -m -r -s
    flake8 .
    py.test tests {posargs}

[flake8]
exclude = .tox,*.egg,build,data
select = E,W,F
